name: Build VergiAI Inspector
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Generate Properties
        run: |
          echo "org.gradle.jvmargs=-Xmx4G" > gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VergiAI-Inspector-Debug
          path: app/build/outputs/apk/debug/*.apk

